#!/usr/bin/env php
<?php

$env = 'dev';

require_once __DIR__.'/vendor/autoload.php';

$app = require __DIR__.'/app/bootstrap_dev.php';
$console = require __DIR__.'/app/console.php';
$console->run();
